require File.expand_path(File.dirname(__FILE__) + '/spec_helper')

describe IndexController do
  describe '/' do
    it 'should be generated by smvc' do
      get '/'
      expect(last_response.body).to include('Find me in controllers/IndexController.rb')
    end
  end
end
